from rsf.proj import*
import fdmod

par={
   'nt':10000,  'ot':0,      'dt':0.001,     'lt':'t',        'ut':'s',
   'nx':1066,   'ox':3.055,  'dx':0.01143,   'lx':'Distance', 'ux':'km',
   'nz':900,    'oz':0.762,  'dz':0.00762,   'lz':'Depth',    'uz':'km' ,
   'kt':100,    'nb':100,    'jsnap':1,      'jdata':1,
    }
fdmod.param(par)

par['xsou']=6.094
par['zsou']=0.762

# source and receviers
fdmod.point('ss',par['xsou'],par['zsou'],par)
fdmod.horizontal('rr',par['oz'],par)

# density
Flow("Fden",None,
'''
spike mag=1 nsp=1 d1=0.00762 d2=0.01143 label1=z label2=x n1=900 n2=1066 o1=0.762 o2=3.055 unit1=km unit2=km
''')

# wavelet
fdmod.wavelet('wav_',15,par)
Flow('wav','wav_','transp')

# FDTD 1
fdmod.awefd('dat','wfl1','wav','Fvel','Fden','ss','rr','free=n jdata=1', par)

End()

