
from rsf.proj import *
import fdmod

###########################################################################################
####################################### RTM/GmRTM #########################################
#################################### source: (7,0) km ##################################### 
################### receiver: (4,0), (5,0), (6,0), (8,0), (9,0), km #######################
###########################################################################################

par={
     'nt':10000,  'ot':0,         'dt':0.001,    'lt':'t', 'ut':'s',
     'nx':564,    'ox':3.055,      'dx':0.01143,  'lx':'x', 'ux':'km',
     'nz':800,    'oz':0.762,     'dz':0.00762,  'lz':'z', 'uz':'km',
     'kt':100,    'nb':100,  'jsnap':1,  'jdata':1
    }
fdmod.param(par)

###########################################################################################
########################################### model #########################################
###########################################################################################

# Source #
Flow('Fsou',None,
'''
spike n1=2 nsp=2 k1=1,2 mag=7,0.762 o1=0 o2=0
''')

# Receiver #
Flow('Frec',None,
     '''
     spike 
     n1=2 n2=5
     nsp=10
     k1=1,2,1,2,1,2,1,2,1,2
     l1=1,2,1,2,1,2,1,2,1,2
     k2=1,1,2,2,3,3,4,4,5,5
     l2=1,1,2,2,3,3,4,4,5,5
     mag=4,0.762,5,0.762,6,0.762,8,0.762,9,0.762
     o1=0 o2=0
     ''')

# Density #
Flow('Fden',None,
     '''
     math output="1"
     n1=%(nz)d o1=%(oz)g d1=%(dz)g
     n2=%(nx)d o2=%(ox)g d2=%(dx)g
     ''' % par)

# Wavelet
fdmod.wavelet('wav_',15,par)
Flow('Fwav', 'wav_','transp')

###########################################################################################
################################### Forward wavefield #####################################
###########################################################################################

fdmod.awefd('Fdat','Fwfl',
            'Fwav',
            'velm','Fden',
            'Fsou','Frec','free=n',par)

###########################################################################################
#################################### Data extraction ######################################
###########################################################################################

# diffraction data extraction #
Flow('D_data1','diffractionCMP','window f2=61  n2=1 f3=99  n3=1 | transp plane=12 | reverse which=2 opt=i')
Flow('D_data2','diffractionCMP','window f2=94  n2=1 f3=66  n3=1 | transp plane=12 | reverse which=2 opt=i')
Flow('D_data3','diffractionCMP','window f2=127 n2=1 f3=33  n3=1 | transp plane=12 | reverse which=2 opt=i')
Flow('D_data4','diffractionCMP','window f2=192 n2=1 f3=33  n3=1 | transp plane=12 | reverse which=2 opt=i')
Flow('D_data5','diffractionCMP','window f2=225 n2=1 f3=66  n3=1 | transp plane=12 | reverse which=2 opt=i')

# original data extraction #
Flow('O_data1','data-cmp','window f2=61  n2=1 f3=99  n3=1 | transp plane=12 | reverse which=2 opt=i')
Flow('O_data2','data-cmp','window f2=94  n2=1 f3=66  n3=1 | transp plane=12 | reverse which=2 opt=i')
Flow('O_data3','data-cmp','window f2=127 n2=1 f3=33  n3=1 | transp plane=12 | reverse which=2 opt=i')
Flow('O_data4','data-cmp','window f2=192 n2=1 f3=33  n3=1 | transp plane=12 | reverse which=2 opt=i')
Flow('O_data5','data-cmp','window f2=225 n2=1 f3=66  n3=1 | transp plane=12 | reverse which=2 opt=i')

###########################################################################################
####################################### RTM&GmRTM #########################################
###########################################################################################

for i in range(1,6,1):
     # Extract the location of receivers #
     Flow('Loc_rec_%d' %i,'Frec',
          '''
          window f2=%d n2=1
          ''' %(i-1))
     # Backward the wave from receivers #
     fdmod.awefd('Tempdata%d' %i,'Bwfl_%d' %i,
                 'D_data%d' %i,
                 'velm','Fden',
                 'Loc_rec_%d' %i,'Fsou','free=n',par)
     fdmod.awefd('Tempdata%d_origin' %i,'Bwfl_%d_origin' %i,
                 'O_data%d' %i,
                 'velm','Fden',
                 'Loc_rec_%d' %i,'Fsou','free=n',par)
     # reverse the wavefield along the tiem axis #
     Flow('Rwfl_%d' %i,'Bwfl_%d' %i,
          '''
          math output="input*1e15" |
          reverse which=4 opt=i verb=y
          ''')
     Flow('Rwfl_%d_rtm' %i,'Bwfl_%d' %i,
          '''
          reverse which=4 opt=i verb=y
          ''')
     Flow('Rwfl_%d_origin' %i,'Bwfl_%d_origin' %i,
          '''
          math output="input*1e15" |
          reverse which=4 opt=i verb=y
          ''')
     Flow('Rwfl_%d_origin_rtm' %i,'Bwfl_%d_origin' %i,
          '''
          reverse which=4 opt=i verb=y
          ''')

# multiply all the backward wavefield #
Flow('Wavefield1',['Rwfl_1', 'Rwfl_2', 'Rwfl_3', 'Rwfl_4', 'Rwfl_5'],
     ''' 
     add mode=p ${SOURCES[1]} ${SOURCES[2]} ${SOURCES[3]} ${SOURCES[4]}

     ''')
Flow('Wavefield1_rtm',['Rwfl_1_rtm', 'Rwfl_2_rtm', 'Rwfl_3_rtm', 'Rwfl_4_rtm', 'Rwfl_5_rtm'],
     ''' 
     add ${SOURCES[1]} ${SOURCES[2]} ${SOURCES[3]} ${SOURCES[4]}

     ''')
Flow('Wavefield1_origin',['Rwfl_1_origin', 'Rwfl_2_origin', 'Rwfl_3_origin', 'Rwfl_4_origin', 'Rwfl_5_origin'],
     ''' 
     add mode=p ${SOURCES[1]} ${SOURCES[2]} ${SOURCES[3]} ${SOURCES[4]}

     ''')
Flow('Wavefield1_origin_rtm',['Rwfl_1_origin_rtm', 'Rwfl_2_origin_rtm', 'Rwfl_3_origin_rtm', 'Rwfl_4_origin_rtm', 'Rwfl_5_origin_rtm'],
     ''' 
     add ${SOURCES[1]} ${SOURCES[2]} ${SOURCES[3]} ${SOURCES[4]}

     ''')

# multiply the forward wavefield #
Flow('Wavefield2',['Wavefield1', 'Fwfl'],
     ''' 
     add mode=p ${SOURCES[1]}

     ''')
Flow('Wavefield2_rtm',['Wavefield1_rtm', 'Fwfl'],
     ''' 
     add mode=p ${SOURCES[1]}

     ''')
Flow('Wavefield2_origin',['Wavefield1_origin', 'Fwfl'],
     ''' 
     add mode=p ${SOURCES[1]}

     ''')
Flow('Wavefield2_origin_rtm',['Wavefield1_origin_rtm', 'Fwfl'],
     ''' 
     add mode=p ${SOURCES[1]}

     ''')


# stack along the time axis #
Flow('image_CRS_GmRTM','Wavefield2',
     '''
     stack axis=3
     ''')
Flow('image_CRS_RTM','Wavefield2_rtm',
     '''
     stack axis=3
     ''')
Flow('image_GmRTM','Wavefield2_origin',
     '''
     stack axis=3
     ''')
Flow('image_RTM','Wavefield2_origin_rtm',
     '''
     stack axis=3
     ''')

###########################################################################################
####################################### Plotting ########################################## 
###########################################################################################

Result('image_CRS_GmRTM',fdmod.cgrey('color=e scalebar=y label1=Depth unit1=km label2=Distance unit2=km ',par))

Result('image_CRS_RTM',fdmod.cgrey('color=e scalebar=y label1=Depth unit1=km label2=Distance unit2=km',par))

Result('image_GmRTM',fdmod.cgrey('color=e  scalebar=y label1=Depth unit1=km label2=Distance unit2=km',par))

Result('image_RTM',fdmod.cgrey('color=e scalebar=y label1=Depth unit1=km label2=Distance unit2=km',par))

Result('Fwfl','sfwindow j3=30 | sfgrey gainpanel=a')

End()
























