from rsf.proj import*

#Source
Flow("Fsou",None,
'''
spike n1=2 nsp=2 k1=1,2 mag=6,0.762 o1=0 o2=0
''')

#Receiver
Flow("Frec",None,
'''
spike 
n1=2 n2=5
nsp=10
k1=1,2,1,2,1,2,1,2,1,2
l1=1,2,1,2,1,2,1,2,1,2
k2=1,1,2,2,3,3,4,4,5,5
l2=1,1,2,2,3,3,4,4,5,5
mag=4,0.762,5,0.762,7,0.762,8,0.762,9,0.762
o1=0 o2=0
''')

#Wavelet
Flow("Fwav",None,
'''
spike nsp=1 n1=10000 d1=0.001 k1=100 | ricker1 frequency=15 | transp
''')

# FDTD Real
Flow("Fdat","Fwav",
'''
awefd2d vel=Fvel.rsf sou=Fsou.rsf rec=Frec.rsf wfl=Fwfl.rsf den=Fden.rsf verb=y free=n expl=y snap=y dabc=y nb=100 jdata=1 jsnap=1
''')

# FDTD migration
Flow("Fdat_","Fwav",
'''
awefd2d vel=Fvelm.rsf sou=Fsou.rsf rec=Frec.rsf wfl=Fwflm.rsf den=Fden.rsf verb=y free=n expl=y snap=y dabc=y nb=100 jdata=1 jsnap=1
''')

# Backward the wave
for i in range(0,5):
	# extract the data from each receiver
	str_num='Fdat'+str(i)
	Flow(str_num,"Fdat",
	'''
	window f1=%d n1=1 verb=y | transp
	'''%i)

	# reverse the data along the time axis
	str_num2='Tdat'+str(i)
	Flow(str_num2,str_num,
	'''reverse which=2 opt=i verb=y
	''')
	
	# extract the receiver locatoin from each receiver
	str_num3='Frec'+str(i)
	Flow(str_num3,"Frec",
	'''
	window f2=%d n2=1 verb=y
	'''%i)

	# Backward the wave from each receiver
	str_num4='RSdat'+str(i)
	str_num5='Twfl'+str(i)
	Flow(str_num4,str_num2,
	'''
	awefd2d vel=Fvelm.rsf sou=%s.rsf rec=Fsou.rsf wfl=%s.rsf den=Fden.rsf verb=y free=n expl=y snap=y dabc=y nb=100 jdata=1 jsnap=1
	'''
	%(str_num3,str_num5))
	
	# reverse the wavefield along the time axis
	str_num6='Mwfl'+str(i)
	Flow(str_num6,str_num5,
	'''
	reverse which=4 opt=i verb=y
	''')
	str_num7='Rwfl'+str(i)
	# multiply the parameter
	Flow(str_num7,None,
	'''
    	sfmath xx1=%s.rsf output='xx1*1e15'
	'''%str_num6)

# multiply all the backward wavefield
Flow("image","Rwfl0",
     ''' 
     add mode=p Rwfl1.rsf Rwfl2.rsf Rwfl3.rsf Rwfl4.rsf

     ''')

# multiply the forward wavefield
Flow("image_","image",
     '''
     add mode=p Fwflm.rsf
     ''')

# stack along the time axis
Flow("ImagingGmRTM","image_",
     '''
     stack axis=3
     ''')

End()
