from rsf.proj import*

#Velocity
Flow("Fvel",None,
'''
spike nsp=1 mag=1.5 n1=900 n2=1599 d1=0.00762 d2=0.00762 o1=0.762 o2=3.048
''')

#spike
Flow("spike",None,
'''
spike nsp=1 n1=15000 d1=0.001 mag=0 
''') 

#Source
Flow("Fsou",None,
'''
spike n1=2 nsp=2 k1=1,2 mag=6,0.762 o1=0 o2=0
''')

#Receiver
Flow("Frec",None,
'''
spike 
n1=2 n2=5
nsp=10
k1=1,2,1,2,1,2,1,2,1,2
l1=1,2,1,2,1,2,1,2,1,2
k2=1,1,2,2,3,3,4,4,5,5
l2=1,1,2,2,3,3,4,4,5,5
mag=4,0.762,5,0.762,7,0.762,8,0.762,9,0.762
o1=0 o2=0
''')

#Wavelet
Flow("Fwav",None,
'''
spike nsp=1 n1=15000 d1=0.001 k1=100 | ricker1 frequency=15 | transp
''')

# FDTD 
Flow("Fdat","Fwav",
'''
awefd2d vel=Fvel.rsf sou=Fsou.rsf rec=Frec.rsf wfl=Fwfl.rsf den=Fden.rsf verb=y free=n expl=y snap=y dabc=y nb=100 jdata=1 jsnap=1
''')

# Backward the wave
for i in range(0,5):
	# noise 
	str_noise='Noise'+str(i)
	Flow(str_noise,"spike",
	'''
	noise range=2 |
	bandpass fhi=30 flo=0 |
	transp
	''')
	# extract the receiver locatoin from each receiver
	str_num1='Frec'+str(i)
	Flow(str_num1,"Frec",
	'''
	window f2=%d n2=1 verb=y
	'''%i)
	# Backward the wave from each receiver
	str_num2='RSdat'+str(i)
	str_num3='Twfl'+str(i)
	Flow(str_num2,str_noise,
	'''
	awefd2d vel=Fvel.rsf sou=%s.rsf rec=Fsou.rsf wfl=%s.rsf den=Fden.rsf verb=y free=n expl=y snap=y dabc=y nb=100 jdata=1 jsnap=1
	'''
	%(str_num1,str_num3))
	
	# reverse the wavefield along the time axis
	str_num4='Rwfl'+str(i)
	Flow(str_num4,str_num3,
	'''
	reverse which=4 opt=i verb=y
	''')

# multiply all the backward wavefield
Flow("image","Rwfl0",
     ''' 
     add Rwfl1.rsf Rwfl2.rsf Rwfl3.rsf Rwfl4.rsf

     ''')

# multiply the forward wavefield
Flow("image_","image",
     '''
     add mode=p Fwfl.rsf
     ''')

# stack along the time axis
Flow("Noise_RTM","image_",
     '''
     stack axis=3
     ''')

End()
