# 3D elastic modeling ( isotropic, different sources?) #

from rsf.proj import *
import fdmod,stiffness

# ------------------------------------------------------------
par = {
    'nt':800,'ot':0, 'dt':0.001, 'lt':'t', 'ut':'s',
    'nx':150, 'ox':0, 'dx':0.01,  'lx':'x', 'ux':'km',
    'ny':150, 'oy':0, 'dy':0.01,  'ly':'y', 'uy':'km',
    'nz':150, 'oz':0, 'dz':0.01,  'lz':'z', 'uz':'km',
    'kt':150,
    'jsnap':1,
    'nb':20,
    'frq':5
    }
fdmod.param(par)
# ------------------------------------------------------------

# ------------------------------------------------------------
fdmod.wavelet('wav_',par['frq'],par)
# ------------------------------------------------------------

# ------------------------------------------------------------
# elastic source
Flow('one','wav_','math output=input*1')

Flow('wave',['one','one','one'],
     '''
     cat axis=2 space=n ${SOURCES[1:3]} |
     transp plane=12 |
     transp plane=23 |
     transp plane=12
     ''')

# ------------------------------------------------------------

# ------------------------------------------------------------
# source/receiver coordinates
fdmod.point3d('ss',
            par['ox']+(par['nx']/2*par['dx']),
            par['oy']+(par['ny']/2*par['dy']),
            par['oz'],par)
fdmod.horizontal3d('rr',0,par)


# ------------------------------------------------------------

# ------------------------------------------------------------
Flow('zero',None,
     '''
     spike nsp=1 mag=0.0
     n1=%(nz)d o1=%(oz)g d1=%(dz)g 
     n2=%(nx)d o2=%(ox)g d2=%(dx)g
     n3=%(ny)d o3=%(oy)g d3=%(dy)g |
     put label1=%(lz)s label2=%(lx)s label3=%(ly)s unit1=%(uz)s unit2=%(ux)s unit3=%(uy)s
     ''' % par) 

Flow('vp','zero','math output="2.0"')
Flow('vs','zero','math output="1.0"')
Flow('ro','zero','math output="2.0"')


stiffness.iso3d('cc','vp','vs','ro',par)

# ------------------------------------------------------------

# ------------------------------------------------------------
# elastic modeling
# same model: isotropic
# different types of source: stress


fdmod.ewefd3d('datu','wflutmp','wave','cc','ro','ss','rr','ssou=y opot=n',par)


Flow('wflu','wflutmp',
     '''
     window
     f1=%(nb)d n1=%(nz)d
     f2=%(nb)d n2=%(ny)d
     f3=%(nb)d n3=%(nx)d
     ''' % par)

End()








































