from rsf.proj import*
Program('Pwesfd2d.x','Pwesfd2d.c')

#Velocity
Flow("Fvel",None,"spike mag=1500,2000,500 nsp=3 k1=1,151,99 l1=150,200,101 k2=1,1,49 l2=200,200,51  d1=4 d2=4 label1=z label2=x n1=200 n2=200 o1=2 o2=2 unit1=m unit2=m")

#Density
Flow("Fden",None,"spike mag=1000,1500,500 nsp=3 k1=1,151,99 l1=150,200,101 k2=1,1,49 l2=200,200,51  d1=4 d2=4 label1=z label2=x n1=200 n2=200 o1=2 o2=2 unit1=m unit2=m")

#Source
Flow("Fsou",None,
     '''
     spike n1=2 nsp=2 k1=1,2 mag=400,0 o1=0 o2=0
     ''')

Flow(['Fwfl','Fvx','Fvz','Fdat'],['Fvel','Fden','Fsou','Pwesfd2d.x'],
     '''
     ./Pwesfd2d.x
     rho=${SOURCES[1]}
     sou=${SOURCES[2]}
     vx=${TARGETS[1]}
     vz=${TARGETS[2]}
     dat=${TARGETS[3]}
     nt=2000
     dt=0.001
     ''')
End()
     
